[package]
name = "memoro_cracker"
version = "1.0.0"
edition = "2021"
authors = ["SlowBearDigger"]

[dependencies]
aes-gcm = "0.10"
argon2 = "0.5"
rayon = "1.10"
hex = "0.4"
base64 = "0.22.1"

[profile.release]
opt-level = 3
lto = true
